server:
  port: 8080
  shutdown: graceful

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:

app:
  jwt-secret: sdfjsf

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
